Include environment name in IAM resources
Tried deploying a publisher for multiple envs and they collided with:

> Error: Error creating IAM Role honeycomb-publisher-logs-role: EntityAlreadyExists: Role with name honeycomb-publisher-logs-role already exists.

Adding the env to the resource names should resolve this.